/*
 * Port_Config.c
 *
 *  Created on: Nov 23, 2019
 *      Author: AhmedShawky
 */

#include "std_types.h"
#include "Priv.h"
#include "Port.h"


const Port_ConfigType PORTA_Config={
		0x00,    /*PortID*/
		0x3f,    /*PortMask,if you are going to use the alternate function use the PortMask to select those pins*/
		0x02,    /* PinsDirectionField */
		0xff,	 /* PinType -> 1 for digital,0 for analog */
		0x02,    /* 2mA configuration */
		0x00,    /* 4mA configuration */
		0x00,    /* 8mA configuration */
		0x00,    /* Open drain configuration */
		0x00,    /* Pull up configuration */
		0x00,    /* Pull down configuration */
};

const Port_ConfigType PORTB_Config={
		0x01,    /*PortID*/
		0x03,    /*PortMask,if you are going to use the alternate function use the PortMask to select those pins*/
		0x02,    /* PinsDirectionField */
		0xff,	 /* PinType -> 1 for digital,0 for analog */
		0x02,    /* 2mA configuration */
		0x00,    /* 4mA configuration */
		0x00,    /* 8mA configuration */
		0x00,    /* Open drain configuration */
		0x00,    /* Pull up configuration */
		0x00,    /* Pull down configuration */
};

const Port_ConfigType PORTC_Config={
		0x02,    /*PortID*/
		0x00,    /*PortMask,if you are going to use the alternate function use the PortMask to select those pins*/
		0xff,    /* PinsDirectionField */
		0xff,	 /* PinType -> 1 for digital,0 for analog */
		0xff,    /* 2mA configuration */
		0x00,    /* 4mA configuration */
		0x00,    /* 8mA configuration */
		0x00,    /* Open drain configuration */
		0x00,    /* Pull up configuration */
		0x00,    /* Pull down configuration */
};

const Port_ConfigType PORTD_Config={
		0x03,    /*PortID*/
		0x00,    /*PortMask,if you are going to use the alternate function use the PortMask to select those pins*/
		0xff,    /* PinsDirectionField */
		0xff,	 /* PinType -> 1 for digital,0 for analog */
		0xff,    /* 2mA configuration */
		0x00,    /* 4mA configuration */
		0x00,    /* 8mA configuration */
		0x00,    /* Open drain configuration */
		0x00,    /* Pull up configuration */
		0x00,    /* Pull down configuration */
};

const Port_ConfigType PORTE_Config={
		0x04,    /*PortID*/
		0x00,    /*PortMask,if you are going to use the alternate function use the PortMask to select those pins*/
		0x3f,    /* PinsDirectionField (THIS PORT IS 6 PINS) */
		0x3f,	 /* PinType -> 1 for digital,0 for analog (THIS PORT IS 6 PINS) */
		0x3f,    /* 2mA configuration (THIS PORT IS 6 PINS) */
		0x00,    /* 4mA configuration (THIS PORT IS 6 PINS) */
		0x00,    /* 8mA configuration (THIS PORT IS 6 PINS) */
		0x00,    /* Open drain configuration (THIS PORT IS 6 PINS) */
		0x00,    /* Pull up configuration (THIS PORT IS 6 PINS) */
		0x00,    /* Pull down configuration (THIS PORT IS 6 PINS) */
};

const Port_ConfigType PORTF_Config={
		0x05,    /*PortID*/
		0x00,    /*PortMask,if you are going to use the alternate function use the PortMask to select those pins*/
		0x1f,    /* PinsDirectionField (THIS PORT IS 5 PINS) */
		0x1f,	 /* PinType -> 1 for digital,0 for analog (THIS PORT IS 5 PINS) */
		0x1f,    /* 2mA configuration (THIS PORT IS 5 PINS) */
		0x00,    /* 4mA configuration (THIS PORT IS 5 PINS) */
		0x00,    /* 8mA configuration (THIS PORT IS 5 PINS) */
		0x00,    /* Open drain configuration (THIS PORT IS 5 PINS) */
		0x00,    /* Pull up configuration (THIS PORT IS 5 PINS) */
		0x00,    /* Pull down configuration (THIS PORT IS 5 PINS) */
};


/*(GPIOIS):THIS SECTION IS FOR INTERRUPT CONFIGURATION, EACH ARRAY INDEX CORRESPONDS TO A PORT'S GPIOIS REGISTER VALUE
IF A BIT IN THE GPIOIS IS SET,THEN THE INTERRUPT DETECTS LEVELS, IF A BIT IS CLEARED THEN IT DETECTS EDGES*/

/*(GPIOIBE):When the corresponding bit in the GPIO Interrupt Sense (GPIOIS) register is set to detect edges, setting a bit in the
GPIOIBE register configures the corresponding pin to detect both rising and falling edges, regardless
of the corresponding bit in the GPIO Interrupt Event (GPIOIEV) register. Clearing
a bit configures the pin to be controlled by the GPIOIEV register.*/

/*(GPIOIEV)Setting a bit in the GPIOIEV register configures the corresponding pin to detect rising edges or high levels,
depending on the corresponding bit value in the GPIO Interrupt Sense (GPIOIS) register.
Clearing a bit configures the pin to detect falling edges or low levels, depending on the corresponding bit value in the GPIOIS*/

/*The GPIOIM register is the interrupt mask register. Setting a bit in the GPIOIM register allows
interrupts that are generated by the corresponding pin to be sent to the interrupt controller on the
combined interrupt signal. Clearing a bit prevents an interrupt on the corresponding pin from being
sent to the interrupt controller. All bits are cleared by a reset.*/



